updpkgsums: include all required files in the sparse checkout
When the `updpkgsums` workflow runs, it initializes a subset of Git for
Windows SDK's repository via a sparse checkout. This subset is defined
in the custom `init-g4w-sdk-for-pacman` Action, and it works well for
`pacman`/`updpkgsums` invocations.

For `makepkg`, however, we need to include the Pacman configuration,
and `gpg.exe`,otherwise the workflow will fail with an error message
like this:

  ==> Checking runtime dependencies...
   error: config file /etc/pacman.conf could not be read: No such file or directory

This happened in this failed workflow run:
https://github.com/git-for-windows/git-for-windows-automation/actions/runs/9415088089/job/25935346092#step:9:87

Fix this by including the Pacman configuration and `gpg.exe in the
sparse checkout.

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>